### ISSUE TITLE
Use flash messages to show errors.

### ISSUE THREAD

**Issue by AliabbasMerchant** [CommunityOfCoders/COCWebsite#1]
We can use the `connect-flash` library

**Comment by ShubhankarKG** [comment]
Is this issue still relevant given that the client has been changed to Reactjs ? Was there a specific need for the flash messages ? If not, I guess we could close this one.

**Comment by AliabbasMerchant** [comment]
Flash Messages were just to show the user about the result of his requests, and errors, if any. Seeing that we are using axios to make requests to the server, we don't exactly need Flash Messages. We can immediately alert the user using toasts or something, about the result of his operations/requests

**Comment by ShubhankarKG** [comment]
Sure enough, thanks for the inputs.

**Comment by ShubhankarKG** [comment]
Closing this as not required anymore.
