### ISSUE TITLE
Navbar UI enhancement

### ISSUE THREAD

**Issue by Saif807380** [CommunityOfCoders/COCWebsite#103]
A few changes are required in the navbar - 
- Right-align all the auth links and left-align everything else
- Navbar overlaps content from various pages
- Navbar should not stick to the top while scrolling
- In mobile view, the hamburger icon isn't visible as both the icon and the backgrounds of a few pages are white in colour

**Comment by akshatshah21** [comment]
For right aligning auth links, we can make a class `nav-item-right` and use the following CSS for it:
```css
.nav-item-right {
  margin-left: auto;
}
```
And then change the `className` of the Login and Logout divs as:
```jsx
className={isDesktop ? `${navItemClass} nav-item-right` : navItemClass}
```
This will look like:
![image](https://user-images.githubusercontent.com/47059039/107519097-d6bf4f00-6bd5-11eb-8d59-332b53e27ee6.png)

**Comment by ShubhankarKG** [comment]
Feel free to have a go at it @akshatshah21
