### ISSUE TITLE
Email validation for new user

### ISSUE THREAD

**Issue by ShubhankarKG** [CommunityOfCoders/COCWebsite#120]
When our new user registers, we don't validate their email address. If someone enters a wrong email ID, our mailer will then try continuously to send mails to a wrong email address, whenever a new event is created.

Solution: Implement email verification. We have a system already that is used for the "Forgot Password" functionality. On similar lines, we can send an email verification link to a new user on signup.

**Comment by utsavk28** [comment]
I would like to work on this
