### ISSUE TITLE
Setup CI pipeline

### ISSUE THREAD

**Issue by ShubhankarKG** [CommunityOfCoders/COCWebsite#13]
CI providers like Travis or CircleCI can be used to check mergeability. We'll have to write tests for that.

**Comment by AtharvaThorve** [comment]
We can also use Github's CI pipelines too.

**Comment by AliabbasMerchant** [comment]
Yup! Anyone willing to set it up?

**Comment by AtharvaThorve** [comment]
@AliabbasMerchant @ShubhankarKG I've created pr for it so would you please review it.

**Comment by AtharvaThorve** [comment]
@ShubhankarKG we can close this issue now.

**Comment by ShubhankarKG** [comment]
Well not until the tests pass I suppose. Can you work on fixing the pipeline please ? :pray:

**Comment by ShubhankarKG** [comment]
Closed via #23
