### ISSUE TITLE
Graduation Year should support Open to All category

### ISSUE THREAD

**Issue by Saif807380** [CommunityOfCoders/COCWebsite#134]
Currently, Add and update event both have graduation year as a field. This field is a text field with validation that the input should be a valid number. However, some events are open to all and this should be allowed to be entered into the field. Also, some events may include students belonging to 2 different graduation years (Skill Up 2.0).

**Comment by akshatshah21** [comment]
For a quick and temporary fix, we could simply remove the regex validation, so the creator can enter strings like "2022, 2023" or "Open to All". But this places the responsibility of a correct input string on the creator. 
AFAIK, the regex validation is at two places: `AddEvent` component and `Events` controller.

**Comment by ShubhankarKG** [comment]
Yes, this is possible. Mind filing a PR @akshatshah21 for this please?
