### ISSUE TITLE
Registered user count of the event is incorrect

### ISSUE THREAD

**Issue by Saif807380** [CommunityOfCoders/COCWebsite#151]
The below function counts the number of registered users for a given event. However, there is no field `users` in the event object. The correct field is `registeredUsers`. Same needs to be changed in the controllers as well

https://github.com/CommunityOfCoders/COCWebsite/blob/f1e2292d933e1e6dc01aa3cfda1faac587d6d26e/server/src/controllers/Events.js#L29

**Comment by sans2801** [comment]
I would like to work on this

**Comment by ShubhankarKG** [comment]
I've assigned you @sans2801

**Comment by ShubhankarKG** [comment]
@sans2801 are you still working on it ?

**Comment by Saif807380** [comment]
> This is the only file that references users/registered users right?

Most likely. However, better to search once. And if there exists another instance, then maybe write a utility that can be used in all places.
