### ISSUE TITLE
[issue]/[feature enhancement] Scrolling issue in dropdown of hamburger menu.

### ISSUE THREAD

**Issue by jatinS-dev** [CommunityOfCoders/COCWebsite#154]
Steps to reproduce the issue
After opening the website when we click on the inspect element and resize the screen to the different dimensions
the drop-down menu is not Scrollable. 

Expected result
The drop-down menu should be scrollable to increase the accessibility of that component.

Actual result
The component is fixed not showing any scroll feature. 

System information (as much as possible)
None

Additional comments
None

**Comment by RaviMauryaHootowl** [comment]
I would like to fix this issue.
