### ISSUE TITLE
Pagination in Events Page

### ISSUE THREAD

**Issue by RaviMauryaHootowl** [CommunityOfCoders/COCWebsite#188]
The events page has no pagination which leads to a long scrolling page. Year-wise pagination can be added just like Alumni Section.

I can take up this issue. Please assign it to me.

**Comment by RaviMauryaHootowl** [comment]
Does this look good? It only shows for the Past Events section. For upcoming events, there is no pagination as there might only be 1 or 2 events.
For Mobile, if there are more years then you can scroll left and right with the finger.

![image](https://user-images.githubusercontent.com/59064326/154495044-7533ed4b-cd50-49dc-9254-4daf79e06a21.png)

![image](https://user-images.githubusercontent.com/59064326/154495373-8c949e54-7e49-4db0-b3e0-5cf8ec5b5115.png)

**Comment by RaviMauryaHootowl** [comment]
@ShubhankarKG

**Comment by ShubhankarKG** [comment]
You can proceed with these designs. Thanks!
