### ISSUE TITLE
New Navbar

### ISSUE THREAD

**Issue by ShubhankarKG** [CommunityOfCoders/COCWebsite#30]
We have been following the navbar as designed earlier, but we need a new design for the navbar, something that is really catchy but not too overtly expressive. We'll need the following **sections** - 
1. Home
2. About Us
3. Events
4. Glimpses
5. Blogs
6. Resources
7. Projects
8. Sign In / Logout

We don't have new designs in mind, so if someone is able to come up with a cool design, we'll encourage that, else we'll put up our own designs.

**Comment by yashtailor** [comment]
How about adding a type writer effect when hovered on each item of navbar. 
Link to type-writer effect: [type-writer-css-tricks](https://css-tricks.com/snippets/css/typewriter-effect/)

**Comment by kkothari2001** [comment]
I can try this out!

**Comment by ShubhankarKG** [comment]
Hey @kkothari2001 , just let us know if you are still on this task :pray: 

Thanks.

**Comment by kkothari2001** [comment]
I have added a PR regarding this

**Comment by ShubhankarKG** [comment]
Per #102, this issue has been resolved. Closing this one out.
