### ISSUE TITLE
Use DB or persistent InMemoryDB for email schedulers

### ISSUE THREAD

**Issue by ShubhankarKG** [CommunityOfCoders/COCWebsite#31]
Lets use MongoDB. We can refer to events by id, and schedule it again, if such an event does not exist.

Considering this is a big change, lets raise an issue for it, and do it in another PR. We can merge this PR once the other points are addressed

_Originally posted by @AliabbasMerchant in https://github.com/CommunityOfCoders/COCWebsite/pull/27#discussion_r493422577_

**Comment by AtharvaThorve** [comment]
We can do something like a user will contain an event id field for which he/she has added the reminder for.

Whenever the server restarts we can schedule the jobs using that field.

**Comment by ShubhankarKG** [comment]
Closed via #116
