### ISSUE TITLE
Navbar overlapping with all events list

### ISSUE THREAD

**Issue by Saif807380** [CommunityOfCoders/COCWebsite#52]
#47 adds a new navbar to the website. However, the page which shows all the events does not take into account the height of the navbar. As a result, the navbar overlaps the list. The same could be true for rest of the pages, but that's yet to be verified. Here's an image of the same, 
<img width="1440" alt="Screenshot 2020-12-23 at 10 33 28" src="https://user-images.githubusercontent.com/50794619/102962519-0e324900-450d-11eb-844a-80acf37b2d11.png">

**Comment by ShubhankarKG** [comment]
Per #103, I think this issue has been resolved. Closing this one out.
