### ISSUE TITLE
Events page optimizations

### ISSUE THREAD

**Issue by ShubhankarKG** [CommunityOfCoders/COCWebsite#56]
1. Add Button should open a modal with `AddEvent` in it.
2. Edit should stay the same I guess since we need the eventId to edit the event.

Caveats:
If a user wishes to close modal, they should be warned that modal close will discard all data.

**Comment by AtharvaThorve** [comment]
@ShubhankarKG Okay, so a modal with the form in it right.

**Comment by ShubhankarKG** [comment]
Yes, that's correct.

**Comment by ShubhankarKG** [comment]
Fixed via #66
