### ISSUE TITLE
Default option shown to a new user is "Logout"

### ISSUE THREAD

**Issue by akshatshah21** [CommunityOfCoders/COCWebsite#61]
I have observed that for a logged out user, the default option shown for auth is "Logout", even though the user has no auth token. The reason is the line 14 shown below. It checks `localStorage.get('token')` for an empty string. It should instead check if it's `null`

https://github.com/CommunityOfCoders/COCWebsite/blob/9a8cc70ba8dab92ee15b267d2848326abcb2c443/new_client/src/reducers/authReducer.js#L12-L18

This might be the same issue as the one mentioned at the end of [this](https://github.com/CommunityOfCoders/COCWebsite/pull/33#issue-504656651) comment

**Comment by ShubhankarKG** [comment]
Thanks for this. Seems like a quick fix should be `!!localStorage.getItem("token")`, to ensure we have truth values only. Do you mind putting up a PR for this?
