### ISSUE TITLE
Remove Some External Stylesheet Links

### ISSUE THREAD

**Issue by akshatshah21** [CommunityOfCoders/COCWebsite#83]
In `new_client/public/index.html`, there are some `<link>` tags that link to CDN stylesheets and fonts:
https://github.com/CommunityOfCoders/COCWebsite/blob/33bf68303b69d3d7bf46ad93055ed943e66621be/new_client/public/index.html#L8-L14

Fonts can be placed in `new_client/src/components/assets`, just like Recharge Bold is already there. This might speed up loading.

Also, there's already the `@material-ui/icons` dependency for icons, so Material Design Icons and Font Awesome links can be removed after changing all usages.

**Comment by ShubhankarKG** [comment]
Nice catch, it looks to me that out of these CDNs, we genuinely require only Roboto. Since we have Material Icons already, both of the CDNs can actually be removed after replacing content.
