### ISSUE TITLE
Typewriter Effect in Home component causes content below it to move vertically

### ISSUE THREAD

**Issue by akshatshah21** [CommunityOfCoders/COCWebsite#89]
On smaller screens (about 370px and lower width), the words in the typewriter effect cause the content below to move up and down:
![typewriter-effect issue](https://user-images.githubusercontent.com/47059039/106424668-9864ba00-6488-11eb-8e79-7d4ac389f811.gif)

This makes scrolling down and reading a little inconvenient.

**Comment by ShubhankarKG** [comment]
Any suggestive ideas here?

**Comment by akshatshah21** [comment]
No. I tried some adjustments, it just isn't working :man_facepalming: Maybe @Leovaldez42 can help out here.

**Comment by Leovaldez42** [comment]
I will look into it.

**Comment by Leovaldez42** [comment]
What if we make the text go to next line at 370 px and lower by adding some css ?

**Comment by AMMAR-62** [comment]
Solved the Issue... just in case if anybody is trying to resolve it and the issue isn't closed
